parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Command\WebsocketServerCommand:
        arguments:
            $websocketPort: '%env(resolve:WEBSOCKET_PORT)%'

    App\Controller\WebsocketController:
        arguments:
            $websocketHost: '%env(resolve:WEBSOCKET_HOST)%'
            $websocketPort: '%env(resolve:WEBSOCKET_PORT)%'
